# Arrays

In [3]:
import numpy as np

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [6]:
# Dot product
v1.dot(v2)

32

In [10]:
A = np.array([[1, 0 , 1], [1, -1, 0], [0, 0, -1]])

In [11]:
# Eigenvalues
np.linalg.eig(A)

(array([-1.,  1., -1.]),
 array([[ 0.00000000e+00,  8.94427191e-01, -2.22044605e-16],
        [ 1.00000000e+00,  4.47213595e-01,  1.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16]]))

In [12]:
# Singular Value Decomposition
np.linalg.svd(A)

(array([[-0.73697623, -0.32798528, -0.59100905],
        [-0.59100905,  0.73697623,  0.32798528],
        [ 0.32798528,  0.59100905, -0.73697623]]),
 array([1.80193774, 1.2469796 , 0.44504187]),
 array([[-0.73697623,  0.32798528, -0.59100905],
        [ 0.32798528, -0.59100905, -0.73697623],
        [-0.59100905, -0.73697623,  0.32798528]]))