# Linear Algebra

In [1]:
import numpy as np

In [21]:
np.random.seed(315) # set random seed to reproduce results
# Creating a random 3x4 matrix
print("Matrix A:\n", A)
A = np.random.rand(3, 4)
print("Matrix B:\n", B)
B = np.random.rand(3, 4)

Matrix A:
 [[0.61667916 0.27916545 0.12567557 0.31564754]
 [0.99690027 0.42309306 0.11248296 0.98173022]
 [0.71999646 0.99945714 0.40981154 0.59635547]]
Matrix B:
 [[0.08731764 0.64646565 0.1383629  0.82447867]
 [0.90655068 0.37345792 0.40047036 0.61835924]
 [0.85632557 0.2508     0.53510871 0.94449822]]


## Slicing the Matrix

In [32]:
# Take row 0 to 1 (not inclusive) and column 0 to 2 (not inclusive)
A[0:1, 0:2]

array([[0.61667916, 0.27916545]])

## Select random rows or columns


In [75]:
rows = np.random.choice(range(3), 2, replace = False)
print("random rows:", rows)
A[rows]

random rows: [2 1]


array([[0.71999646, 0.99945714, 0.40981154, 0.59635547],
       [0.99690027, 0.42309306, 0.11248296, 0.98173022]])