# Markov Information Source Model

Example from Dr. Hiroki Sayama's Computational Tools course
SSIE500, Binghamton University, 2020

<img src="images/markov-weather.png">

In [48]:
import numpy as np
from math import log2

| | Sunny | Cloudy | Rainy |
|--|--|--|--|
|Sunny|0.6|0.3|0.3|
|Cloudy|0.3|0.4|0.5|
|Rainy|0.1|0.3|0.2|

In [3]:
# First row: incoming probabilities to Sunny
# Second row: incoming probabilities to Cloudy
# Third row: incoming probabilities to Rainy
tpm = np.array([
    [0.6, 0.3, 0.3],
    [0.3, 0.4, 0.5],
    [0.1, 0.3, 0.2]
])

In [24]:
# Calculate eigenvalues
eigensystem = np.linalg.eig(tpm)
print(eigensystem)

(array([ 1. ,  0.3, -0.1]), array([[-7.10870190e-01, -8.16496581e-01,  1.08367999e-16],
       [-6.24704106e-01,  4.08248290e-01, -7.07106781e-01],
       [-3.23122814e-01,  4.08248290e-01,  7.07106781e-01]]))


In [25]:
# np.linalg.eigh(tpm)

In [26]:
# Take the dominant eigenvector (vector which corresponds to eigenvalue 1)
eigenvector = eigensystem[1][:,0]
print(eigenvector)

[-0.71087019 -0.62470411 -0.32312281]


In [46]:
# Normalize to make a probability distribution (sums to 1).
# This will be the long term probability distribution.
print("Long run probability distribution:")
print([e/sum(eigenvector) for e in eigenvector])
probs = [e/sum(eigenvector) for e in eigenvector]

Long run probability distribution:
[0.42857142857142855, 0.3766233766233766, 0.19480519480519481]


In [45]:
# Today is sunny
v = np.array([1, 0, 0])
# Probability distribution 5 days from now (dot product 5 times)
tpm.dot(tpm.dot(tpm.dot(tpm.dot(tpm.dot(v)))))

array([0.42996, 0.37593, 0.19411])

In [47]:
# Generate a sequence of weather
# weather_dist = list(zip(["S", "C", "R"], probs))
list(zip(["S", "C", "R"], probs))

[('S', 0.42857142857142855),
 ('C', 0.3766233766233766),
 ('R', 0.19480519480519481)]

## Calculating Entropy of Markov Information Source

In [51]:
def entropy(x_):
    return sum([-1.0*p*log2(p) for p in x_])

entropy([0.5, 0.25, 0.25])

1.5

In [55]:
# Transpose the transition probability matrix
tpm_T = np.transpose(tpm)

h = np.apply_along_axis(entropy, 1, tpm_T)
h
# If today's weather is sunny, you have 1.29 bits of uncertainty for tomorrow's weather
# If today's weather is rainy, you have 1.57 bits of uncertainty for tomorrow's weather
# If today's weather is cloudy, you have 1.48 bits of uncertainty for tomorrow's weather

array([1.29546184, 1.57095059, 1.4854753 ])

In [60]:
# Final entropy
print("The amount of entropy this system produces:")
print("(Expected value of state entropy)")
h.dot(probs)

The amount of entropy this system produces:
(Expected value of state entropy)


1.4362329552916886