## Statistical Complexity

Calculate the entropy rate and the statistical complexity of the following Markov information source

In [14]:
import numpy as np
import random

The next state will be:

    - 1 if the previous three states were 000
    - 0 if the previous three states were 111
    - randomly selected from {0, 1} otherwise

In [2]:
states = []

# How many previous steps to consider when changing states?
history = 3

# Seed values to initialize the Markov information source
# Must have num. of elements as the history set above
seed = (0, 0, 0)

states.extend(seed)

print("Markov Information source\n")
print("Initial conditions:")
print(states)

Markov Information source

Initial conditions:
[0, 0, 0]


In [3]:
def get_history(states: list, num_steps: int):
    """
    Return the previous `num_steps` steps from a list of states.
    """
    history = states[-num_steps:]
    return history

In [4]:
print("`get_history` function unit test\n")
print("Inputs:")
print("states = [0, 0, 1, 0, 0, 1, 0, 1]")
print("num_steps = 3")
print("\n")
print("Expected output:")
print("[1, 0, 1]")

`get_history` function unit test

Inputs:
states = [0, 0, 1, 0, 0, 1, 0, 1]
num_steps = 3


Expected output:
[1, 0, 1]


In [5]:
states = [0, 0, 1, 0, 0, 1, 0, 1]
num_steps = 3
get_history(states, num_steps)

[1, 0, 1]

In [6]:
def generate_state(states: list):
    """
    Next state generated according to:
        1 if previous three states were 000
        0 if previous three states were 111
        randomly chosen from {0,1} otherwise
    
    Returns:
        updated list of states
        tuple of tuples: (history 3 states, updated 3 states)
    """
    # Get previous history
    prev_states = get_history(states, 3)
    
    # Generate next state
    if prev_states == [0,0,0]:
        next_state = 1
    elif prev_states == [1,1,1]:
        next_state = 0
    else:
        next_state = random.randint(0,1)
    
    # Update states
    states.append(next_state)
    
    causal_pair = (tuple(prev_states), tuple(states[-3:]))
    
#     print(states)
    
    return states, causal_pair

In [7]:
print("`generate_state` function unit test\n")
print("Input:")
print("states = [0, 0, 1, 1, 1, 0, 0, 0]")
print("\n")
print("Expected output:")
print("[0, 0, 1, 1, 1, 0, 0, 0, 1]")

`generate_state` function unit test

Input:
states = [0, 0, 1, 1, 1, 0, 0, 0]


Expected output:
[0, 0, 1, 1, 1, 0, 0, 0, 1]


In [8]:
states = [0, 0, 1, 1, 1, 0, 0, 0]
generate_state(states)

([0, 0, 1, 1, 1, 0, 0, 0, 1], ((0, 0, 0), (0, 0, 1)))

### Reset experiment and set up new conditions

In [146]:
# Reset initial conditions
del states
del history
del seed

# Set initial conditions
states = []

# How many previous steps to consider when changing states?
history = 3

# Seed values to initialize the Markov information source
# Must have num. of elements as the history set above
seed = (0, 0, 0)

states.extend(seed)

print("Markov Information source\n")
print("Initial conditions:")
print(states)

# Set number of steps to run
n = 20000

print("\nNum. steps:", n)

Markov Information source

Initial conditions:
[0, 0, 0]

Num. steps: 20000


In [133]:
# help from https://stackoverflow.com/a/61296855
def causals_transition_matrix(causals: list):
    """
    Calculates the probability distribution from a
        list of causals from a Markov information source.
        
    Returns:
        Numpy array of transition probabilities
            Rows are causals
            Columns are next states
        Ordered list of states used to create array
    """
    # TO DO:
    #   Need to aggregate states. this is lossy! (intentionally)
    
    # Generate set of transition pairs
#     state_pair_sets = list(set(causals))
#     print(state_pair_sets)
    
    tran_probs = {pair:causals.count(pair)/len(causals) for pair in causals}
#     print(tran_probs)
    rows = [state[0] for state in causals]
    columns = [state[1] for state in causals]
    
    states = list(set(rows + columns))
    
    tpm = np.zeros((len(states), len(states)))
     
    for pair in tran_probs.keys():
        i = states.index(pair[0])
        j = states.index(pair[1])
        tpm[i, j] = tran_probs[pair]
    
    return tpm, states

test_causals = [
    ((0, 0, 0), (0, 0, 1)),
    ((0, 0, 0), (0, 0, 1)),
    ((0, 1, 1), (0, 0, 0)),
    ((0, 1, 0), (1, 0, 0)),
    ((1, 1, 0), (0, 1, 0))
]

print(causals_transition_matrix(test_causals))

(array([[0. , 0.2, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. , 0. ]]), [(1, 1, 0), (0, 1, 0), (0, 0, 0), (1, 0, 0), (0, 0, 1), (0, 1, 1)])


In [147]:
def simulate():
    causals = []

    # Collect causal pairs for each generation
    for i in range(n):
        causals.append(generate_state(states)[1])

        # Final state generated
        if i == n-1:
            final_state = generate_state(states)
            
            print("Final state:")
            print(final_state)
            print("\nCausals:")
            print(causals)
    
    return final_state, causals
            
final, causals = simulate()

Final state:
([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0

In [148]:
# Create probabilty transition matrix from causals
c_tpm = causals_transition_matrix(causals)
print(c_tpm[0])
eigensystem = np.linalg.eig(c_tpm[0])
eigenvector = eigensystem[1][:,0]
print(eigenvector)
print("Long run probability distribution:")
print([e/sum(eigenvector) for e in eigenvector])
probs = [e/sum(eigenvector) for e in eigenvector]
# print(probs)

[[0.      0.      0.0732  0.      0.      0.      0.      0.07125]
 [0.07185 0.      0.      0.      0.07175 0.      0.      0.     ]
 [0.0726  0.      0.      0.      0.0691  0.      0.      0.     ]
 [0.      0.      0.      0.      0.      0.07225 0.      0.     ]
 [0.      0.      0.      0.0722  0.      0.06865 0.      0.     ]
 [0.      0.      0.06855 0.      0.      0.      0.      0.07235]
 [0.      0.07265 0.      0.      0.      0.      0.      0.     ]
 [0.      0.07095 0.      0.      0.      0.      0.07265 0.     ]]
[-0.41493526+0.j -0.40974972+0.j -0.40538384+0.j -0.2222541 +0.j
 -0.33352325+0.j -0.40347658+0.j -0.22695925+0.j -0.34736053+0.j]
Long run probability distribution:
[(0.1501407138783851-0j), (0.1482643707225522-0j), (0.14668461571009603-0j), (0.0804207108483705-0j), (0.12068248574266338-0j), (0.14599448880916271-0j), (0.0821232279791043-0j), (0.12568938630966575-0j)]
